// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,val:38, set:40, push:42, get:42, dup:42, swap:42, shrink:42, truncate:42, add:42, sub:42, mul:42, div:42, mod:42, neg:42, inc:42, dec:42, gt:42, lt:42, ge:42, le:42, eq:42, neq:42, shl:42, shr:42, rol:42, ror:42, and:42, or:42, xor:42, not:42, pow:42, powi:42, powf:42, sin:42, cos:42, tan:42, sinh:42, cosh:42, tanh:42, asin:42, acos:42, atan:42, atan2:42, asinh:42, acosh:42, atanh:42, sqrt:42, cbrt:42, ln:42, log2:42, log10:42, exp:42, print:42, println:42, stdin:42, stdout:42, stdoutln:42, clear_screen:42, break:42, nop:42, jump:42, if_false:42, func:42, call:42, return:42, stop:42, make_obj:42, make_array:42, access:42, access_index:42, length:42, typeof:42, concat:42, import:42, export:42, set_prop:42, instantiate:42, inspect_obj:42, inspect_array:42, to_short:42, to_integer:42, to_long:42, to_octa:42, to_half:42, to_float:42, to_double:42, to_string:42, sht:44, int:44, lng:44, oct:44, hlf:44, flt:44, dbl:44, str:44, i16:44, i32:44, i64:44, i128:44, f16:44, f32:44, f64:44}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!vQQOPOOOOOO'#C^'#C^OOOO'#C`'#C`OOOO'#Ca'#CaOOOO'#Cb'#CbOOOO'#Ce'#CeOOOO'#Cf'#CfOOOO'#Cg'#CgOOOO'#Ch'#ChOOOO'#Ci'#CiOOOO'#Cj'#CjOOOO'#Cm'#CmQQOPOOOOOO-E6k-E6k",
  stateData: "!`~ORZOVZOWZO_ZO`ZOcPOdQOeROfSOgTOhUOiVOjWOkXOlYO~ORVW_ghijkl`h~",
  goto: "mbPPcPcccPPccccccPPgTZO[Q[OR][",
  nodeNames: "⚠ Document ValKeyword Identifier SetKeyword Opcode PrimitiveType Number String OpenSquareBracket CloseSquareBracket OpenBrace CloseBrace OpenParenthesis CloseParenthesis Comment Character",
  maxTerm: 28,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "*f~RiOr!prs!usw!pwx$}xy'Qyz'Xz!Q!p!Q!['`![!]!p!]!^(W!^!c!p!c!}(z!}#O)p#O#P!p#P#Q)w#Q#R!p#R#S(z#S#T!p#T#o(z#o#p*O#p#q!p#q#r*V#r;'S!p;'S;=`*^;=`O!p~!uO`~~!zV`~Or#ars#ys#O#a#O#P$O#P;'S#a;'S;=`$w<%lO#a~#dVOr#ars#ys#O#a#O#P$O#P;'S#a;'S;=`$w<%lO#a~$OOW~~$RRO;'S#a;'S;=`$[;=`O#a~$_WOr#ars#ys#O#a#O#P$O#P;'S#a;'S;=`$w;=`<%l#a<%lO#a~$zP;=`<%l#a~%SV`~Ow%iwx#yx#O%i#O#P&R#P;'S%i;'S;=`&z<%lO%i~%lVOw%iwx#yx#O%i#O#P&R#P;'S%i;'S;=`&z<%lO%i~&URO;'S%i;'S;=`&_;=`O%i~&bWOw%iwx#yx#O%i#O#P&R#P;'S%i;'S;=`&z;=`<%l%i<%lO%i~&}P;=`<%l%i~'XOk~`~~'`Ol~`~~'gQV~`~!O!P'm!Q!['{~'pP!Q!['s~'xPV~!Q!['s~(QQV~!O!P'm!Q!['{~(]P`~!]!^(`~(eT_~OY(`Z](`^;'S(`;'S;=`(t<%lO(`~(wP;=`<%l(`~)RSR~`~!Q![)_!c!})_#R#S)_#T#o)_~)dSR~!Q![)_!c!})_#R#S)_#T#o)_~)wOg~`~~*OOh~`~~*VOi~`~~*^Oj~`~~*cP`~;=`<%l!p",
  tokenizers: [0],
  topRules: {"Document":[0,1]},
  specialized: [{term: 3, get: (value: keyof typeof spec_Identifier) => spec_Identifier[value] || -1}],
  tokenPrec: 49
})
