// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,val:36, set:38, push:40, get:40, dup:40, swap:40, shrink:40, truncate:40, add:40, sub:40, mul:40, div:40, mod:40, neg:40, inc:40, dec:40, gt:40, lt:40, ge:40, le:40, eq:40, neq:40, shl:40, shr:40, rol:40, ror:40, and:40, or:40, xor:40, not:40, pow:40, powi:40, powf:40, sin:40, cos:40, tan:40, sinh:40, cosh:40, tanh:40, asin:40, acos:40, atan:40, atan2:40, asinh:40, acosh:40, atanh:40, sqrt:40, cbrt:40, ln:40, log2:40, log10:40, exp:40, print:40, println:40, stdin:40, stdout:40, stdoutln:40, clear_screen:40, break:40, nop:40, jump:40, if_false:40, func:40, call:40, return:40, stop:40, make_obj:40, make_array:40, access:40, access_index:40, length:40, typeof:40, concat:40, import:40, export:40, set_prop:40, instantiate:40, inspect_obj:40, inspect_array:40, to_short:40, to_integer:40, to_long:40, to_octa:40, to_half:40, to_float:40, to_double:40, to_string:40, sht:42, int:42, lng:42, oct:42, hlf:42, flt:42, dbl:42, str:42, i16:42, i32:42, i64:42, i128:42, f16:42, f32:42, f64:42}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!vQQOPOOOOOO'#C^'#C^OOOO'#C`'#C`OOOO'#Ca'#CaOOOO'#Cb'#CbOOOO'#Ce'#CeOOOO'#Cf'#CfOOOO'#Cg'#CgOOOO'#Ch'#ChOOOO'#Ci'#CiOOOO'#Cj'#CjOOOO'#Cl'#ClQQOPOOOOOO-E6j-E6j",
  stateData: "![~ORZOVZOWZO_ZObPOcQOdROeSOfTOgUOhVOiWOjXOkYO~ORVWfghijk_h~",
  goto: "laPPbPbbbPPbbbbbbPfTZO[Q[OR][",
  nodeNames: "⚠ Document ValKeyword Identifier SetKeyword Opcode PrimitiveType Number String OpenSquareBracket CloseSquareBracket OpenBrace CloseBrace OpenParenthesis CloseParenthesis Character",
  maxTerm: 27,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: ")l~RgOr!jrs!osw!jwx$wxy&zyz'Rz!Q!j!Q!['Y![!c!j!c!}(Q!}#O(v#O#P!j#P#Q(}#Q#R!j#R#S(Q#S#T!j#T#o(Q#o#p)U#p#q!j#q#r)]#r;'S!j;'S;=`)d;=`O!j~!oO_~~!tV_~Or#Zrs#ss#O#Z#O#P#x#P;'S#Z;'S;=`$q<%lO#Z~#^VOr#Zrs#ss#O#Z#O#P#x#P;'S#Z;'S;=`$q<%lO#Z~#xOW~~#{RO;'S#Z;'S;=`$U;=`O#Z~$XWOr#Zrs#ss#O#Z#O#P#x#P;'S#Z;'S;=`$q;=`<%l#Z<%lO#Z~$tP;=`<%l#Z~$|V_~Ow%cwx#sx#O%c#O#P%{#P;'S%c;'S;=`&t<%lO%c~%fVOw%cwx#sx#O%c#O#P%{#P;'S%c;'S;=`&t<%lO%c~&ORO;'S%c;'S;=`&X;=`O%c~&[WOw%cwx#sx#O%c#O#P%{#P;'S%c;'S;=`&t;=`<%l%c<%lO%c~&wP;=`<%l%c~'ROj~_~~'YOk~_~~'aQV~_~!O!P'g!Q!['u~'jP!Q!['m~'rPV~!Q!['m~'zQV~!O!P'g!Q!['u~(XSR~_~!Q![(e!c!}(e#R#S(e#T#o(e~(jSR~!Q![(e!c!}(e#R#S(e#T#o(e~(}Of~_~~)UOg~_~~)]Oh~_~~)dOi~_~~)iP_~;=`<%l!j",
  tokenizers: [0],
  topRules: {"Document":[0,1]},
  specialized: [{term: 3, get: (value: keyof typeof spec_Identifier) => spec_Identifier[value] || -1}],
  tokenPrec: 46
})
