// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Document = 1,
  ValKeyword = 2,
  Identifier = 3,
  SetKeyword = 4,
  Opcode = 5,
  PrimitiveType = 6,
  Number = 7,
  String = 8,
  OpenSquareBracket = 9,
  CloseSquareBracket = 10,
  OpenBrace = 11,
  CloseBrace = 12,
  OpenParenthesis = 13,
  CloseParenthesis = 14,
  Comment = 15,
  Character = 16
