// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,val:20, set:22, push:24, get:24, dup:24, swap:24, shrink:24, truncate:24, add:24, sub:24, mul:24, div:24, mod:24, neg:24, inc:24, dec:24, gt:24, lt:24, ge:24, le:24, eq:24, neq:24, shl:24, shr:24, rol:24, ror:24, and:24, or:24, xor:24, not:24, pow:24, powi:24, powf:24, sin:24, cos:24, tan:24, sinh:24, cosh:24, tanh:24, asin:24, acos:24, atan:24, atan2:24, asinh:24, acosh:24, atanh:24, sqrt:24, cbrt:24, ln:24, log2:24, log10:24, exp:24, print:24, println:24, stdin:24, stdout:24, stdoutln:24, clear_screen:24, break:24, nop:24, jump:24, if_false:24, func:24, call:24, return:24, stop:24, make_obj:24, make_array:24, access:24, access_index:24, length:24, typeof:24, concat:24, import:24, export:24, set_prop:24, instantiate:24, inspect_obj:24, inspect_array:24, to_short:24, to_integer:24, to_long:24, to_octa:24, to_half:24, to_float:24, to_double:24, to_string:24, sht:26, int:26, lng:26, oct:26, hlf:26, flt:26, dbl:26, str:26, i16:26, i32:26, i64:26, i128:26, f16:26, f32:26, f64:26}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!QQQOPOOOOOO'#C^'#C^OOOO'#C`'#C`OOOO'#Ca'#CaOOOO'#Cb'#CbOOOO'#Cd'#CdQQOPOOOOOO-E6b-E6b",
  stateData: "i~ORTOVTOYPOZQO[RO]SO~ORV~",
  goto: "dXPPYPYYYP^TTOUQUORVU",
  nodeNames: "⚠ Document ValKeyword Identifier SetKeyword Opcode PrimitiveType Character",
  maxTerm: 13,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "!q~RXO!cn!c!}s!}#Rn#R#Ss#S#Tn#T#os#o;'Sn;'S;=`!i;=`On~sOV~~zSR~V~!Q![!W!c!}!W#R#S!W#T#o!W~!]SR~!Q![!W!c!}!W#R#S!W#T#o!W~!nPV~;=`<%ln",
  tokenizers: [0],
  topRules: {"Document":[0,1]},
  specialized: [{term: 3, get: (value: keyof typeof spec_Identifier) => spec_Identifier[value] || -1}],
  tokenPrec: 22
})
