// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Document = 1,
  Opcode = 2,
  Identifier = 3,
  PrimitiveType = 4,
  Number = 5,
  String = 6,
  OpenSquareBracket = 7,
  CloseSquareBracket = 8,
  OpenBrace = 9,
  CloseBrace = 10,
  OpenParenthesis = 11,
  CloseParenthesis = 12,
  Comment = 13,
  Character = 14
