// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,val:34, set:34, push:34, get:34, dup:34, swap:34, shrink:34, truncate:34, add:34, sub:34, mul:34, div:34, mod:34, neg:34, inc:34, dec:34, gt:34, lt:34, ge:34, le:34, eq:34, neq:34, shl:34, shr:34, rol:34, ror:34, and:34, or:34, xor:34, not:34, pow:34, powi:34, powf:34, sin:34, cos:34, tan:34, sinh:34, cosh:34, tanh:34, asin:34, acos:34, atan:34, atan2:34, asinh:34, acosh:34, atanh:34, sqrt:34, cbrt:34, ln:34, log2:34, log10:34, exp:34, print:34, println:34, stdin:34, stdout:34, stdoutln:34, clear_screen:34, break:34, nop:34, jump:34, if_false:34, func:34, call:34, return:34, stop:34, make_obj:34, make_array:34, access:34, access_index:34, length:34, typeof:34, concat:34, import:34, export:34, set_prop:34, instantiate:34, inspect_obj:34, inspect_array:34, to_short:34, to_integer:34, to_long:34, to_octa:34, to_half:34, to_float:34, to_double:34, to_string:34, sht:36, int:36, lng:36, oct:36, hlf:36, flt:36, dbl:36, str:36, i16:36, i32:36, i64:36, i128:36, f16:36, f32:36, f64:36}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!jQQOPOOOOOO'#C^'#C^OOOO'#C`'#C`OOOO'#Cc'#CcOOOO'#Cd'#CdOOOO'#Ce'#CeOOOO'#Cf'#CfOOOO'#Cg'#CgOOOO'#Ch'#ChOOOO'#Ck'#CkQQOPOOOOOO-E6i-E6i",
  stateData: "!Y~ORXOTXOUXO]XO^XOaPObQOcROdSOeTOfUOgVOhWO~ORTU]cdefgh^d~",
  goto: "k`PPaPaPPaaaaaaPPeTXOYQYORZY",
  nodeNames: "⚠ Document Opcode Identifier PrimitiveType Number String OpenSquareBracket CloseSquareBracket OpenBrace CloseBrace OpenParenthesis CloseParenthesis Comment Character",
  maxTerm: 24,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "*f~RiOr!prs!usw!pwx$}xy'Qyz'Xz!Q!p!Q!['`![!]!p!]!^(W!^!c!p!c!}(z!}#O)p#O#P!p#P#Q)w#Q#R!p#R#S(z#S#T!p#T#o(z#o#p*O#p#q!p#q#r*V#r;'S!p;'S;=`*^;=`O!p~!uO^~~!zV^~Or#ars#ys#O#a#O#P$O#P;'S#a;'S;=`$w<%lO#a~#dVOr#ars#ys#O#a#O#P$O#P;'S#a;'S;=`$w<%lO#a~$OOU~~$RRO;'S#a;'S;=`$[;=`O#a~$_WOr#ars#ys#O#a#O#P$O#P;'S#a;'S;=`$w;=`<%l#a<%lO#a~$zP;=`<%l#a~%SV^~Ow%iwx#yx#O%i#O#P&R#P;'S%i;'S;=`&z<%lO%i~%lVOw%iwx#yx#O%i#O#P&R#P;'S%i;'S;=`&z<%lO%i~&URO;'S%i;'S;=`&_;=`O%i~&bWOw%iwx#yx#O%i#O#P&R#P;'S%i;'S;=`&z;=`<%l%i<%lO%i~&}P;=`<%l%i~'XOg~^~~'`Oh~^~~'gQT~^~!O!P'm!Q!['{~'pP!Q!['s~'xPT~!Q!['s~(QQT~!O!P'm!Q!['{~(]P^~!]!^(`~(eT]~OY(`Z](`^;'S(`;'S;=`(t<%lO(`~(wP;=`<%l(`~)RSR~^~!Q![)_!c!})_#R#S)_#T#o)_~)dSR~!Q![)_!c!})_#R#S)_#T#o)_~)wOc~^~~*OOd~^~~*VOe~^~~*^Of~^~~*cP^~;=`<%l!p",
  tokenizers: [0],
  topRules: {"Document":[0,1]},
  specialized: [{term: 3, get: (value: keyof typeof spec_Identifier) => spec_Identifier[value] || -1}],
  tokenPrec: 43
})
